# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_regis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('favlistManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Triplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_product', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_regis.User')),
            ],
            managers=[
                ('triplanManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='favlist',
            name='triplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triplan.Triplan'),
        ),
        migrations.AddField(
            model_name='favlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_regis.User'),
        ),
    ]
