# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triplan', '0003_auto_20160703_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triplan',
            name='user',
        ),
    ]
