# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_regis', '0002_auto_20160703_0543'),
        ('triplan', '0004_remove_triplan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='triplan',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login_regis.User'),
            preserve_default=False,
        ),
    ]
