# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triplan', '0005_triplan_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='favlist',
            managers=[
            ],
        ),
    ]
